server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-micro
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: inventory-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
